// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChl6a1LQqKZJf_7payOea-tKwP802dVmQ',
    appId: '1:562207652524:web:db2835dbfb76355908fd09',
    messagingSenderId: '562207652524',
    projectId: 'dieklingel',
    authDomain: 'dieklingel.firebaseapp.com',
    storageBucket: 'dieklingel.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzvQFc_eaEpd46Oq2ifhaqcQcppUMrOH4',
    appId: '1:562207652524:android:934bae104838271508fd09',
    messagingSenderId: '562207652524',
    projectId: 'dieklingel',
    storageBucket: 'dieklingel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdMKFOz_DrOHohCUWjFejjlqpyiiTwAV0',
    appId: '1:562207652524:ios:573c77c806f853a008fd09',
    messagingSenderId: '562207652524',
    projectId: 'dieklingel',
    storageBucket: 'dieklingel.appspot.com',
    iosClientId: '562207652524-2vt2o57m45889r68jd0862bed5uu8v82.apps.googleusercontent.com',
    iosBundleId: 'com.dieklingel.app',
  );
}
