# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Buidl and sign the IPA package."
  lane :build do
    setup_ci
    match(app_identifier: ["com.dieklingel.app"], type: "appstore", readonly: is_ci)
    Dir.chdir("../../") do
      sh("flutter pub get")
      sh("flutter build ipa --export-options-plist=ios/ExportOptions.plist")
    end
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci
    match(app_identifier: ["com.dieklingel.app"], type: "appstore", readonly: is_ci)
    Dir.chdir("../../") do
      sh("flutter pub get")
      sh("flutter build ipa --export-options-plist=ios/ExportOptions.plist")
    end

    api_key = app_store_connect_api_key(
      key_id: ENV['API_KEY_ID'],
      issuer_id: ENV['ISSUER_ID'],
      key_content: ENV['API_KEY'],
      duration: 1200, # optional (maximum 1200)
      in_house: false
    )

    upload_to_testflight(
      api_key: api_key,
      ipa: "../build/ios/ipa/dieklingel_app.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end
