name: "Run Tests and Build for Web/Android/iOS"
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  flutter-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.4'
          channel: 'stable'
      
      - name: Install Pubs
        run: flutter pub get

      - name: Run Tests
        run: flutter test

  flutter-build-webapp:
    runs-on: ubuntu-latest
    needs: [flutter-test]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.4'
          channel: 'stable'
      
      - name: Install Pubs
        run: flutter pub get

      - name: Run Tests
        run: flutter build web --release

  flutter-build-apk:
    runs-on: ubuntu-latest
    needs: [flutter-test]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.4'
          channel: 'stable'
      
      - name: Install Pubs
        run: flutter pub get

      - name: Run Tests
        run: flutter build apk --release

  flutter-build-ipa:
    runs-on: macos-latest
    needs: [flutter-test]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.4'
          channel: 'stable'
      
      - name: Install Pubs
        run: flutter pub get

      - name: Run Tests
        run: flutter build ios --release --no-codesign
