
name: build-webapp
on:
  push:
    branches:
      - main
jobs:
  build-flutter:
    runs-on: ubuntu-latest
    env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: build/web
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE: "Build: ({sha}) {msg}"
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web
      - run: echo "app.dieklingel.de" > build/web/CNAME
      - uses: s0/git-publish-subdir-action@develop
