
name: check-tests
on:
  pull_request:
    branches:
      - main
      - development
jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.3'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test
