
name: check-build
on:
  pull_request:
    branches:
      - main
      - development
jobs:
  check-build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.3'
          channel: 'stable'
      - run: |
            flutter pub get
            flutter test
            flutter build web
            flutter build apk
            flutter build ios --no-codesign
