
name: Build, sign and deploy the ios app to TestFlight.
on:
  push:
    branches:
      - feature/ci-ipa
jobs:
  deploy-ios-app:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.3'
          channel: 'stable'

      - name: Install the Apple certificate and provisioning profile
        env:
          APPLE_DISTRIBUTION_CERTIFICATE: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE }}
          APPLE_DISTRIBUTION_CERTIFICATE_PW: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE_PW }}
          PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}
          PROVISIONING_PROFILE_IMAGE_NOTIFICATION: ${{ secrets.PROVISIONING_PROFILE_IMAGE_NOTIFICATION }}
          KEYCHAIN_PW: ${{ secrets.KEYCHAIN_PW }}
        run: |
          # import certificates
          echo $APPLE_DISTRIBUTION_CERTIFICATE | base64 --decode --output certificate.p12
          echo $PROVISIONING_PROFILE | base64 --decode --output pp.mobileprovision
          echo $PROVISIONING_PROFILE_IMAGE_NOTIFICATION | base64 --decode --output pp_ext.mobileprovision
          security create-keychain -p $KEYCHAIN_PW build.keychain
          security set-keychain-settings -lut 21600 build.keychain
          security unlock-keychain -p $KEYCHAIN_PW build.keychain
          # import certificate to keychain
          security import certificate.p12 -P $APPLE_DISTRIBUTION_CERTIFICATE_PW -A -t cert -f pkcs12 -k build.keychain
          security list-keychain -d user -s build.keychain
          # profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp pp.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles
          cp pp_ext.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Install Pubs
        run: flutter pub get

      - name: Build ipa in release mode
        run: flutter build ipa --release

      - name: Clean up keychain and provisioning profile
        if: ${{ always() }}
        run: |
          security delete-keychain build.keychain
          rm ~/Library/MobileDevice/Provisioning\ Profiles/pp.mobileprovision
          rm ~/Library/MobileDevice/Provisioning\ Profiles/pp_ext.mobileprovision
