
name: Build, sign and deploy the ios app to TestFlight.
on:
  push:
    branches:
      - main
      - feature/ios-fastlane
jobs:
  deploy-ios-app:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.3'
          channel: 'stable'

      - name: Install the signing certificate and provisioning profile
        env:
          APPLE_DISTRIBUTION_CERTIFICATE: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE }}
          APPLE_DISTRIBUTION_CERTIFICATE_PW: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE_PW }}
          PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}
          PROVISIONING_PROFILE_IMAGE_NOTIFICATION: ${{ secrets.PROVISIONING_PROFILE_IMAGE_NOTIFICATION }}
          KEYCHAIN_PW: ${{ secrets.KEYCHAIN_PW }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: |
          cd ios
          fastlane beta
