name: TestFlight
on:
  push:
    branches:
      - main

jobs:
  deploy-ios-app:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.6"
          channel: "stable"

      - name: Build and Publish IPA to Testflight
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_ID: ${{ secrets.API_KEY_ID }}
          ISSUER_ID: ${{ secrets.ISSUER_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        run: |
          cd ios
          fastlane beta
